version: 1

project:
  root: .
  build_config: lzc-build.yml
  package_file: package.yml
  output: dist/community.lazycat.app.zerotier.lpk
  target_arch: amd64

update:
  strategy: publish
  allow_downgrade: false
  version_source:
    type: image
    image: zerotier

build:
  toolchains: []
  run_buildscript: false

images:
  - id: zerotier
    target: service
    service: zerotier
    source: docker.io/zyclonite/zerotier
    channel: stable
    sort: semver
    tag_regex: '^v?\d+\.\d+\.\d+$'
    delivery:
      mode: lazycat

stores:
  official:
    enabled: true
    continue_if_newer_version: true
    skip_if_version_exists: true
    retry:
      enabled: false
  private:
    enabled: true
    skip_if_version_exists: true
    name: ZeroTier
    summary: Published from GitHub Actions
